# Workflow при создании запроса на вливание в ветку, название которой начинается с "main",
# запускает следующие задания:
# - проверку синтаксиса и code style с помощью модуля flake8 (останавливает выполнение при наличии синтаксических ошибок);
# - модульные тесты фреймворка unittest, запускается файл test_runner.py, если файл не найден, запускаются все найденные тесты;
# - время, отведенное на выполнение проверок, составляет 5 минут.

# Workflow для веток, название которых начинается с "implemented",
# запускает те же проверки при каждом push.

name: Python auto testing

on:
  pull_request:
    branches:
      - "main*" 
  push:
    branches:
      - "implemented*" 
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5 
    steps:
    - uses: actions/checkout@v3 

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # Останавливает выполнение при наличии синтаксических ошибок или неопределенных имен
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero рассматривает все ошибки как предупреждения
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Test with unittest module
      run: |
        # Если файл test_runner.py существует, запускает его
        # Иначе запускает все найденные тесты
        if [ -f test_runner.py ]; then
          python3 -m unittest test_runner.py
        else
          python3 -m unittest
        fi